### ISSUE TITLE
et2更新这个模组就报错，

### ISSUE THREAD

**Issue by wsfjm** [friendlyhj/ZenUtils#14]
报错内容[ERROR] contenttweaker\item\AdvancedFruit.zs:47 > No such member in mods.contenttweaker.MutableItemStack: setTag
[zenutils-1.7.4]是最后一个可以使用的版本，只要高过这个版本他就出错，要怎么修

**Comment by friendlyhj** [comment]
那行换成 `item.mutable().updateTag({soulbindUUID: player.getUUID()});`
