### ISSUE TITLE
[Question] `EntityRemoveEvent` how to stop hopper?

### ISSUE THREAD

**Issue by Krutoy242** [friendlyhj/ZenUtils#25]
I have custom crafting mechanic of turning `Seared Stone` into ore by dropping items in it.

[Source code](https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/7ebc7086ad2270eb8992287c29ba3235047bea10/scripts/do/burnt_in_fluid.zs#L69-L109) of mechanic. Im using `EntityRemoveEvent` to determine, when item get burned in lava-like Seared Stone so i could transform it (with 30% chance).

<img src="https://github.com/friendlyhj/ZenUtils/assets/936618/8c11bdab-da27-40f8-a362-0f467ef697cb" width=400>

The problem happens when there is Hopper under Seared Stone block.
To reproduce:
1. Place hopper under lava
2. Drop item inside lava block (im using vanilla Dropper)
3. `EntityRemoveEvent` fired
4. I can't stop hopper to consume that item programmatically

![image](https://github.com/friendlyhj/ZenUtils/assets/936618/0942196d-18ee-4bed-b72b-d1db0c1aa09e)

I tried to remove entity from world or set it size to `0`, but nothing helps and after event, item still consumed
```less
  entityItem.item.mutable().withAmount(0);
  world.removeEntity(e.entity);
```

I know there is note that event cant be cancelled. But its there other way to check what consuming item? Like, separate event from "Item destroyed by lava" and "Item pulled by hopper" ?

**Comment by friendlyhj** [comment]
So EntityItemDeathEvent added, it is fired when an entity item "dies" of damage. (fire or void etc.) Listen it and check if the damage source is `inFire`.

**Comment by Krutoy242** [comment]
Big thanks! This would make my code even cleanier.
