### ISSUE TITLE
[Feature Request] Check if block is in loaded chunk

### ISSUE THREAD

**Issue by Krutoy242** [friendlyhj/ZenUtils#27]
Using `CraftTweaker` and `ZenUtils` I made Portal Spread mechanic.

When portal is spawned, it saved with `setCustomWorldData()`. Then I iterate all portals in `onWorldTick` event.

https://github.com/friendlyhj/ZenUtils/assets/936618/8269985d-15e3-4890-a3eb-502891566044

The problem is that `CraftTweaker`'s functions always load chunks for calls like `world.getBlockState()`. So, each time i want to tick the portal, it would call `getBlockState` and actually work as chunk loader.

**Please, add function to check if block is in loaded chunk.**

With such function I could check if portal is in loaded chunk and tick it only if loaded.

**Comment by friendlyhj** [comment]
Added in CraftTweaker/CraftTweaker#1685

**Comment by Krutoy242** [comment]
Incredible! 😲
