### ISSUE TITLE
Conflict with FTB Utilities

### ISSUE THREAD

**Issue by Sereath** [friendlyhj/ZenUtils#38]
After updating from 1.16.9 to 1.17.0 some change caused FTB Utilities healing button at the top left of the screen when opening the inventory to stop restoring players properly. It still heals them, but it wont replenish the hunger anymore. And now it also starts printing: /heal < player>, in the in-game chat.

One log:
https://gist.github.com/Sereath/1159346b463429b7d7e1eafc7abadb31

Expected from FTB Utilities healing button:
Heal
Restore hunger

With 1.17.0:
Heal
No hunger restoration
Now prints ingame /heal < player>

**Comment by friendlyhj** [comment]
I believe I didn't make any game-play changes between 1.16.9 and 1.17.0. And I can't reproduce it in the latest version.
