### ISSUE TITLE
Can you add a player analog handheld item? 【能不能给加个模拟手持物品？】

### ISSUE THREAD

**Issue by chenming0v0** [friendlyhj/ZenUtils#39]
I saw a lot of statements that simulated the player in the "Player Interaction Simulation", but there was no statement that simulated the player holding an item, so please strengthen the "ZenUtilsPlayer", thank you
在Player Interaction Simulation里面看到了很多模拟玩家的语句，但是没有模拟玩家手持物品的语句,求加强ZenUtilsPlayer

**Comment by Shibva** [comment]
I wanna assume this is is straightforward and to the point, but can you give an example or two to further elaborate on what you mean

**Comment by friendlyhj** [comment]
```zenscript
val originItem = player.getItemInSlot(hand);
player.setItemInSlot(item);
// do your stuff between the two lines
player.setItemInSlot(originItem);
```
