### ISSUE TITLE
Native Method Access

### ISSUE THREAD

**Issue by friendlyhj** [friendlyhj/ZenUtils#45]
I know this is an insane idea, but it's worth having a try.
- [x] Native method and field access
- [x] Wrap interface static methods to deal with weird bytecode issues
- [x] Conversion between native objects and crafttweaker wrappers
- [x] Filter dangerous classes
- [x] Remap methods by mcp
- [ ] #60
- [x] Handle all Forge events to Generic Event Manager
- [x] Use `foo` getter / setter to invoke `getFoo` `setFoo` native methods
- [x] Allow expansion method to native classes

**Comment by Krutoy242** [comment]
Subscribed.
