### ISSUE TITLE
[Feature Request] expose GUI open event

### ISSUE THREAD

**Issue by Krutoy242** [friendlyhj/ZenUtils#53]
I want to detect when player "acquire" important items and their functionality.
I found, that if I want to detect complicated stuff like EnderIO `Conduits` I cannot propertly do this with already existed events:

1. I cant detect from crafting because player can autocraft it.
2. I cant detect from placing since player could just use block placers.
3. I should not detect from `PlayerInteractBlockEvent` since it would cause false-positive when you accidentally clicked conduit on spawn or just stand too far from block and GUI cancelled.
4. I cannot detect when player using some weird mechanics that opening GUIs on trigger.

I think, event that expose gui name or something similar would be cool.
I dont know if its possible to expose more information, like if its *Inventory* GUI and such, but would be good for the future too.

![image](https://github.com/friendlyhj/ZenUtils/assets/936618/005999d8-0a70-4857-98a3-f2a74eca8d78)

**Comment by friendlyhj** [comment]
Try this?
https://docs.blamejared.com/1.12/en/Vanilla/Events/Events/PlayerOpenContainer

**Comment by Krutoy242** [comment]
Oh, yes, its working.. I cant cancel it through, but i think i could use this. Thank you. I really looked through every event possible several times, but somehow missed it 😅

**Comment by friendlyhj** [comment]
In `v1.19.0`, you can subscribe all forge events.
```zenscript
#sideonly client
// this a client only event, your script should be client only too.

events.register(function(event as native.net.minecraftforge.client.event.GuiOpenEvent) {
    // your code
});
```

**Comment by friendlyhj** [comment]
It is a forge issue. `GuiOpenEvent` cancellation doesn't work for gui that contains data sync (e.g. item slots). The event only denies the gui from displayed, but it doesn't stop data sync. Server still try to sync the gui contents to client. After you cancel the event, the gui of server and client is different: furance on server side while player invenrory on client side, then the data sync logic produces desync instead. (yea, gui is client only exactly, the thing on server side is called container, to deal with data sync)
So I suggested to PlayerOpenContainer event previously, but it is not cancelable :(

I tried send packet to notify server to close the gui connection. But it takes time, the gui still displayes in one tick.

So even I expose GuiOpenEvent, there still isn't a good way to deny opening a gui. It's better to find a reliable way to use `PlayerInteractBlockEvent`

**Comment by Krutoy242** [comment]
> I tried to send packet to notify server to close the gui connection. But it takes time, the gui still displayes in one tick.

This solution is actually sounds reliable. Glitchy but players will understand that this happened intentionally. How i could do that with CT?

**Comment by friendlyhj** [comment]
```zenscript
import mods.zenutils.NetworkHandler;

// in client only script
events.register(function(event as native.net.minecraftforge.client.event.GuiOpenEvent) {
    val guiClass = typeof(event.getGui());
    if ( guiClass == 'net.minecraft.client.gui.inventory.GuiFurnace') {
        NetworkHandler.sendToServer("close_container");
    }
});

// in a plain script
NetworkHandler.registerClient2ServerMessage("close_container", function(server, byteBuf, player) {
    player.native.closeScreen();
});
```

**Comment by friendlyhj** [comment]
Oh, wait, `PlayerOpenContainerEvent` + `closeScreen` works prefectly
```zenscript
events.register(function(event as crafttweaker.event.PlayerOpenContainerEvent) {
    if (event.container.asString().startsWith("net.minecraft.inventory.ContainerFurnace")) {
        event.player.native.closeScreen();
    }
});
```
