### ISSUE TITLE
[Feature Request] Iterate/list loaded chunks

### ISSUE THREAD

**Issue by Krutoy242** [friendlyhj/ZenUtils#54]
I added new feature with ZS - planets where Blood Magic meteors spawning naturally and bombarding planet surface.

The problem is that ZS **can't properly find random chunk** - I used ["hack" with onBlockNeighborNotify](https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/scripts/mods/bloodmagic/meteor.zs#L60) to randomly chose one of the chunks when this event happens, since planet is full of liquids that regularly raising this event.

So, my request is to **list all loaded chunks in a world** or **pick random loaded chunk in a world**.

P.S. **List all loaded chunks** would be also handy for creating custom commands to detect mechanics that keeps chunk loaded due bugs.

![image](https://github.com/friendlyhj/ZenUtils/assets/936618/f6ac4822-09b9-491e-bcd6-35d9a51ab984)

**Comment by friendlyhj** [comment]
I have to expose many things about chunk for it...
Hmm, I would not like to make such repetitive labour, you can trace #45. I'm working for it now. Close this issue for now.
