### ISSUE TITLE
Cannot get native java List as a returning value; Got zenscript's array instead

### ISSUE THREAD

**Issue by tttsaurus** [friendlyhj/ZenUtils#64]
The zs code is trying to append a new message to items' tooltip. (zenutils 1.19.1)
```
#reloadable

import mods.zenutils.EventPriority;
import native.net.minecraftforge.event.entity.player.ItemTooltipEvent;

events.register(function(event as ItemTooltipEvent) 
{
    event.getToolTip().add("test");

}, EventPriority.lowest(), true);
```
The result (failed): 
![image](https://github.com/user-attachments/assets/2d44d834-08fa-4c51-9b54-f1b7f0e8b545)

Major problems:
1. List.add() method is not available, which means the returned value isn't a java.util.List
2. changing the value of zenscript's array doesn't do anything since the reference is lost

Forge documentation indicates that getToolTip() returns List<String>
![image](https://github.com/user-attachments/assets/8a22aa0b-3127-4932-8d8b-16d4c8bca80b)
https://hauteknits.github.io/ForgeJavaDocs-NG/javadoc/1.12.2/net/minecraftforge/event/entity/player/ItemTooltipEvent.html

Is there any hidden castings in zenutils, maybe?

**Comment by friendlyhj** [comment]
Yes, `java.util.List` is not a native type. It is already registered as array list type of zenscript. For your usage instance, you can use `modifyTooltip`. (not on wiki)
```zenscript
<*>.modifyTooltip(function(item, tooltip, shiftPressed, advanced) {
    tooltip.add("test");
}
```

And zs array list does have `add` operation. Use `+=` to add an element.

```zenscript
#reloadable

import mods.zenutils.EventPriority;
import native.net.minecraftforge.event.entity.player.ItemTooltipEvent;

events.register(function(event as ItemTooltipEvent) 
{
    var tooltip as [string] = event.getToolTip();
    tooltip += "test";
}, EventPriority.lowest(), true);
```

But zs list only has `add` `remove` `contains` `get` `size` operation. I should make it can use all `java.util.List` methods.

**Comment by tttsaurus** [comment]
Got it. Thank you
